repos:
  - repo: local
    hooks:
      - id: isort
        args: [--combine-as]
        name: isort
        entry: isort
        language: system
        types: [ python ]
        files: ^(duckingit/|tests/)
        require_serial: true
      - id: black
        name: black
        entry: black --line-length 100
        language: system
        types: [ python ]
        require_serial: true
        files: ^(duckingit/|tests/)
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [ python ]
        files: ^(duckingit/|tests/)
        require_serial: true