site_name: DUCKING IT
site_url: https://duckingit.io/
repo_name: tobiasegelund/duckingit
extra_css:
  - assets/css/extra.css

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/favicon.png

  icon:
    repo: fontawesome/brands/git-alt

  features:
    - navigation.instant
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    # - navigation.footer
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - content.action.edit
    - content.action.view

  palette:
    - primary: white
    - accent: blue

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tobiasegelund

plugins:
  - search

nav:
    - Home: home.md
    - Setup: setup.md
    - Tutorial: tutorial.md
    - Documentation: documentation.md
    - Release: release.md