FROM public.ecr.aws/lambda/python:3.9

# Install Python dependencies
RUN pip3 install duckdb --target "${LAMBDA_TASK_ROOT}"

# Install HTTPFS
COPY install.py ${LAMBDA_TASK_ROOT}
RUN python3 ${LAMBDA_TASK_ROOT}/install.py

COPY lambda_handler.py .

CMD [ "lambda_handler.handler" ]
